# This is a basic workflow to help you get started with Actions
name: Release Build
on:
  release:
    branches:
      -master
 
jobs:
  release:
    name: Release to NuGet
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
          
      - name: Build
        run: dotnet build -c Release
                      
      - name: Build, Pack, and Publish
        uses: rohith/publish-nuget@v2
        #uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/PreviewHandler.Sdk.Managed/PreviewHandler.Sdk.Managed.csproj
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        
    
